### ISSUE TITLE
Outdated component docs

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag-docs#116]
# 🐛 Bug report

1. Component docs are outdated, showing information that's no longer relevant.
2. Docs claim they're for the latest version of each component, although that is not the case.

## 💥 Steps to reproduce

Visit any component doc page under the [Zag Docs page](https://zagjs.com/)

## 💻 Link to reproduction

https://zagjs.com/components/react/menu
For the `Menu` component as an example

## 🧐 Expected behavior

Docs are synced with the latest version on npm.
Docs don't claim an older version is latest.

## 📝 Additional information
Hover card docs claiming 0.1.6 is the latest version:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/23258552/214847481-48998ea3-cf16-46f1-b779-dc2489ca27b0.png">

Although clicking it leads to npm, where 0.2.0 is the current version:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/23258552/214847657-d3821641-0106-455b-b0ac-2cfbf91af29f.png">

Menu card docs detailing menu api methods & properties:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/23258552/214847768-b173b73d-fc86-45ae-8f4f-ff9e726b01f8.png">

Although as seen on npm, `activeId` property and `setActiveId` method no longer exists, and are now called `highlightedId` and `setHighlightedId` respectively:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/23258552/214848276-9f72d2fc-889f-4993-b2d1-d1e00c94ec03.png">

**Comment by segunadebayo** [comment]
Thanks for raising this issue.

Based on my PR here https://github.com/chakra-ui/zag-docs/pull/126, we update the docs automatically based on the zag-js codebase.

Regarding the version mismatch, this will be resolved when we merge the auto-created PRs created from the GH actions in the zag.js repo. cc @anubra266
