### ISSUE TITLE
[DatePicker] Missing Docs for date-picker

### ISSUE THREAD

**Issue by HadiSDev** [chakra-ui/zag-docs#133]
Hi.

I think the docs for date-picker is missing. I can see the machine exists, but I have no idea on how to use it :/

**Comment by segunadebayo** [comment]
The date picker is not a public yet. It's a work in progress, when it's done we'll add some docs for it.

**Comment by HadiSDev** [comment]
Sorry my bad. Good luck with it. How far are you with it if you don't mind me asking? 😊
