### ISSUE TITLE
[Tabs] Usage code snippet is incorrect

### ISSUE THREAD

**Issue by mryechkin** [chakra-ui/zag-docs#26]
Trying to run the [Tabs example](https://zagjs.com/components/react/tabs#usage) results in an error, as it appears to be referencing outdated function names:

<img width="1097" alt="Screen Shot 2022-05-15 at 11 42 20 AM" src="https://user-images.githubusercontent.com/5657181/168481395-6e47f4cc-7dbf-4eb1-ab8c-ef9c5f1586bc.png">

The following should be changed:
- `tablistProps` -> `triggerGroupProps`
- `getTabProps` -> `getTriggerProps`
- `getTabPanelProps ` -> `getContentProps`

The following code works:

```jsx
const [state, send] = useMachine(tabs.machine({ value: 'item-1' }));
const ref = useSetup({ send, id: '1' });
const api = tabs.connect(state, send);

return (
  <div ref={ref}>
    <div {...api.triggerGroupProps}>
      {data.map((item) => (
        <button {...api.getTriggerProps({ value: item.value })} key={item.value}>
          {item.label}
        </button>
      ))}
    </div>
    {data.map((item) => (
      <div {...api.getContentProps({ value: item.value })} key={item.value}>
        <p>{item.content}</p>
      </div>
    ))}
  </div>
);
```

**Comment by segunadebayo** [comment]
Good catch @mryechkin!

We've updated the docs for tabs to use the up-to-date APIs

**Comment by mryechkin** [comment]
Thanks @segunadebayo!

I just realized that the same goes for styling and all the names used in `data-part`s - it should be `trigger` instead of `tab` etc.

Do you want me to log another ticket for this?
